# -*- coding: utf-8 -*-

KList=[
('animaciya-films' ,'Анимация'),
('art-haus' ,'Арт-хаус, Авторское'),
('biography' ,'Биография'),
('action' ,'Боевик'),
('boevye' ,'Боевые искусства'),
('western' ,'Вестерн'),
('voenniy' ,'Военный'),
('detective' ,'Детектив'),
('detskiy' ,'Детский'),
('documental' ,'Документальный'),
('drama' ,'Драма'),
('history' ,'Исторический'),
('katastrofa' ,'Катастрофа'),
('comedy' ,'Комедия'),
('short' ,'Короткометражный'),
('criminal' ,'Криминал'),
('melodrama' ,'Мелодрама'),
('mystic' ,'Мистика'),
('vmusic' ,'Музыка'),
('musical' ,'Мюзикл'),
('nemoe' ,'Немое кино'),
('noir' ,'Нуар'),
('parody' ,'Пародия'),
('adventure' ,'Приключения'),
('roman' ,'Роман'),
('russian' ,'Русский фильм'),
('family' ,'Семейный'),
('skazka' ,'Сказка'),
('soviet' ,'Советский фильм'),
('spektakl' ,'Спектакль'),
('sport' ,'Спорт'),
('triller' ,'Триллер'),
('horror' ,'Ужасы'),
('scifiction' ,'Фантастика'),
('fantasy' ,'Фэнтези'),
('sex' ,'Эротика')
]

SList=[
('foreign-tv//tv' ,'Зарубежный сериал'),
('russian-tv//tv' ,'Русский сериал'),
('biography//tv' ,'Биография'),
('action//tv' ,'Боевик'),
('boevye//tv' ,'Боевые искусства'),
('western//tv' ,'Вестерн'),
('voenniy//tv' ,'Военный'),
('detective//tv' ,'Детектив'),
('detskiy//tv' ,'Детский'),
('documental//tv' ,'Документальный'),
('drama//tv' ,'Драма'),
('history//tv' ,'Исторический'),
('comedy//tv' ,'Комедия'),
('short//tv' ,'Короткометражный'),
('criminal//tv' ,'Криминал'),
('melodrama//tv' ,'Мелодрама'),
('mystic//tv' ,'Мистика'),
('vmusic//tv' ,'Музыка'),
('musical//tv' ,'Мюзикл'),
('noir//tv' ,'Нуар'),
('adventure//tv' ,'Приключения'),
('roman//tv' ,'Роман'),
('family//tv' ,'Семейный'),
('skazka//tv' ,'Сказка'),
('sport//tv' ,'Спорт'),
('triller//tv' ,'Триллер'),
('horror//tv' ,'Ужасы'),
('scifiction//tv' ,'Фантастика'),
('fantasy//tv' ,'Фэнтези'),
('sex//tv' ,'Эротика')
]

AList=[
('anime//multfilm' ,'Аниме'),
('anime-serialy//multfilm' ,'Аниме сериалы'),
('zarubezhnye-multfilmy//multfilm' ,'Зарубежные мультфильмы'),
('multserialy//multfilm' ,'Мультсериалы'),
('russkie-multfilmy//multfilm' ,'Русские мультфильмы'),
('art-haus//multfilm' ,'Арт-хаус, Авторское'),
('biography//multfilm' ,'Биография'),
('action//multfilm' ,'Боевик'),
('western//multfilm' ,'Вестерн'),
('voenniy//multfilm' ,'Военный'),
('detective//multfilm' ,'Детектив'),
('detskiy//multfilm' ,'Детский'),
('dlya-vzroslyh//multfilm' ,'Для взрослых'),
('documental//multfilm' ,'Документальный'),
('drama//multfilm' ,'Драма'),
('history//multfilm' ,'Исторический'),
('short//multfilm' ,'Короткометражный'),
('criminal//multfilm' ,'Криминал'),
('melodrama//multfilm' ,'Мелодрама'),
('vmusic//multfilm' ,'Музыка'),
('musical//multfilm' ,'Мюзикл'),
('parody//multfilm' ,'Пародия'),
('roman//multfilm' ,'Роман'),
('family//multfilm' ,'Семейный'),
('skazka//multfilm' ,'Сказка'),
('spektakl//multfilm' ,'Спектакль'),
('sport//multfilm' ,'Спорт'),
('triller//multfilm' ,'Триллер'),
('scifiction//multfilm' ,'Фантастика'),
('fantasy//multfilm' ,'Фэнтези'),
('sex//multfilm' ,'Эротика')
]

TList=[
('animaciya-films//documentary' ,'Анимация'),
('biography//documentary' ,'Биография'),
('vidovoj//documentary' ,'Видовой'),
('voenniy//documentary' ,'Военный'),
('gipotezy//documentary' ,'Гипотезы'),
('dokumentalnye-serialy//documentary' ,'Документальные сериалы'),
('documental//documentary' ,'Документальный'),
('dopolnitelnye-materialy//documentary' ,'Дополнительные материалы'),
('zagadki-istorii//documentary' ,'Загадки истории'),
('zemlya//documentary' ,'Земля'),
('iskusstvo//documentary' ,'Искусство'),
('history//documentary' ,'Исторический'),
('katastrofa//documentary' ,'Катастрофа'),
('short//documentary' ,'Короткометражный'),
('kosmos//documentary' ,'Космос'),
('kulinariya//documentary' ,'Кулинария'),
('lichnosti//documentary' ,'Личности'),
('vmusic//documentary' ,'Музыка'),
('muzykalnye-programmy//documentary' ,'Музыкальные программы'),
('nauka-i-tehnologii//documentary' ,'Наука и технологии'),
('priroda-i-zhivotnye//documentary' ,'Природа и животные'),
('puteshestviya//documentary' ,'Путешествия'),
('rassledovaniya//documentary' ,'Расследования'),
('religiya//documentary' ,'Религия'),
('socium//documentary' ,'Социум'),
('sport//documentary' ,'Спорт'),
('tehnika//documentary' ,'Техника'),
('uvlecheniya//documentary' ,'Увлечения'),
('scifiction//documentary' ,'Фантастика'),
('fenomen//documentary' ,'Феномен'),
('ceremonii-nagrazhdeniya//documentary' ,'Церемонии награждения'),
('civilizacii//documentary' ,'Цивилизации'),
('chelovek//documentary' ,'Человек'),
('evolyuciya//documentary' ,'Эволюция'),
('ekstrim//documentary' ,'Экстрим'),
('sex//documentary' ,'Эротика')
]

MList=[
('videoklipy//music' ,'Видеоклипы'),
('koncertnoe-video//music' ,'Концертное видео')
]

TgList=[
('all//tag//3d' ,'3D'),
('all//tag//hdtv-1080i' ,'HDTV//HDTVRip 1080i'),
('all//tag//hdtv-720p' ,'HDTV//HDTVRip 720p'),
('all//tag//nauchnaya-fantastika' ,'Sci-Fi (Научная фантастика)'),
('all//tag//be-continued' ,'to be continued...'),
('all//tag//avangard-i-syurrealizm' ,'Авангард и Сюрреализм'),
('all//tag//anime' ,'Аниме'),
('all//tag//antiutopiya' ,'Антиутопия'),
('all//tag//vampiry' ,'Вампиры'),
('all//tag//gangstery' ,'Гангстеры'),
('all//tag//zombi' ,'Зомби'),
('all//tag//indijskoe-kino' ,'Индийское кино'),
('all//tag//kiberpank' ,'Киберпанк'),
('all//tag//kollekciya' ,'Коллекция'),
('all//tag//komiks' ,'Комикс'),
('all//tag//narkotiki' ,'Наркотики'),
('all//tag//novogodnie' ,'Новогодние'),
('all//tag//oborotni' ,'Оборотни'),
('all//tag//parallelnye-miry' ,'Параллельные миры'),
('all//tag//peplum' ,'Пеплум'),
('all//tag//perevod-goblina' ,'Перевод Гоблина'),
('all//tag//podrostkovaya-zhestokost' ,'Подростковая жестокость'),
('all//tag//postapokalipsis' ,'Постапокалипсис'),
('all//tag//prizraki' ,'Призраки'),
('all//tag//prishelcy' ,'Пришельцы'),
('all//tag//psevdodokumentalnyj' ,'Псевдодокументальный'),
('all//tag//puteshestviya-vo-vremeni' ,'Путешествия во времени'),
('all//tag//rezhisserskaya-versiya' ,'Режиссерская версия'),
('all//tag//relaks' ,'Релакс'),
('all//tag//slesher' ,'Слэшер'),
('all//tag//tancy' ,'Танцы'),
('all//tag//tyurma' ,'Тюрьма'),
('all//tag//fanaty-i-skinhedy' ,'Фанаты и Скинхеды'),
('all//tag//ekranizaciya' ,'Экранизация'),
('all//tag//trash-tresh-movies' ,'trash movies')
]