# -*- coding: utf-8 -*-
CnlDict={
"1+1": "1+1",
"2+2": "2+2",
"24 док": "24 ДОК",
"24 техно": "24 Техно",
"2x2": "2x2",
"365": "365",
"5 канал": "5 канал",
"8 канал": "8 Канал",
"ab moteurs": "AB Moteurs",
"ajara tv": "Ajara TV",
"amazing life": "Amazing Life",
"amedia": "AMEDIA",
"animal planet hd": "Animal Planet HD",
"animal planet": "Animal Planet",
"a-one": "A-ONE",
"axn sci-fi": "AXN Sci-Fi",
"baby tv": "Baby TV",
"bbc entertainment": "BBC Entertainment",
"bbc world": "BBC World",
"bbc": "BBC",
"biztv": "BizTV",
"bloomberg": "Bloomberg",
"boomerang": "Boomerang",
"bridge tv": "BRIDGE TV",
"c music tv": "C Music TV",
"cartoon network": "Cartoon Network",
"cbs drama": "CBS Drama",
"cbs reality": "CBS Reality",
"cnbc": "CNBC",
"cnn": "CNN",
"da vinci": "Da Vinci",
"deutsche welle": "Deutsche Welle",
"discovery channel": "Discovery Channel",
"discovery hd showcase": "Discovery HD Showcase",
"discovery science": "Discovery Science",
"discovery world": "Discovery World",
"discovery восточная европа": "Discovery Восточная Европа",
"diva universal": "DIVA Universal",
"encyclo": "ENCYCLO",
"english club tv": "English Club TV",
"enter-фильм": "Enter-фильм",
"espn classic": "ESPN classic",
"euronews": "EuroNews",
"europa plus tv": "Europa Plus TV",
"eurosport 2": "Eurosport 2",
"eurosport hd": "Eurosport HD",
"eurosport": "Eurosport",
"extreme sports": "Extreme Sports",
"fashion one": "Fashion One",
"fashion tv hd": "Fashion TV HD",
"fashion tv": "Fashion TV",
"fine living network": "Fine Living Network",
"fox life hd": "Fox Life HD",
"fox life": "Fox Life",
"fox": "FOX",
"france 24": "France 24",
"galaxy tv": "Galaxy TV",
"gulli": "Gulli",
"hd life": "HD Life",
"hd кино 2": "HD КИНО 2",
"hd кино": "HD КИНО",
"hd медиа": "HD Медиа",
"hd спорт": "HD Спорт",
"iconcerts": "iConcerts",
"ictv": "ICTV",
"ictv украина": "ICTV",
"investigation discovery": "Investigation Discovery",
"jimjam": "JimJam",
"kidsco": "KidsCo",
"luxe hd": "Luxe HD",
"luxe.tv": "Luxe.TV",
"man tv": "Man TV",
"mcm pop": "MCM POP",
"mcm top": "MCM TOP",
"mezzo live hd": "Mezzo Live HD",
"mezzo": "Mezzo",
"mgm hd": "MGM HD",
"mgm": "MGM",
"motors tv": "Motors TV",
"mtv dance": "MTV Dance",
"mtv european": "MTV European",
"mtv hits": "MTV Hits",
"mtv live hd": "MTV Live HD",
"mtv music": "MTV Music",
"mtv rocks": "MTV Rocks",
"mtv": "MTV",
"musicbox ru": "MusicBox RU",
"musicbox tv": "MusicBox TV",
"myzen.tv": "myZen.tv",
"myzen.tv hd": "myZen.tv",
"nat geo wild hd": "Nat Geo Wild HD",
"nat geo wild": "Nat Geo WILD",
"national geographic hd": "National Geographic HD",
"national geographic": "National Geographic",
"newsone": "NewsOne",
"nhk world tv": "NHK WORLD TV",
"nick jr": "Nick Jr",
"nickelodeon hd": "Nickelodeon HD",
"nickelodeon": "Nickelodeon",
"ocean tv": "Ocean TV",
"o-tv": "O-TV",
"outdoor channel": "Outdoor Channel",
"paramount comedy": "Paramount Comedy",
"pro business": "PRO Business",
"pro все": "Pro все",
"ru.tv": "Ru.TV",
"rusong tv": "Rusong TV",
"russia today": "Russia Today",
"russian travel guide": "Russian Travel Guide",
"sony turbo": "Sony Turbo",
"sony тв": "SONY ТВ",
"stv": "STV",
"style tv": "Style TV",
"tdk": "TDK",
"tiji": "TiJi",
"tlc": "TLC",
"trace urban": "Trace Urban",
"tv xxi": "TV XXI",
"tv1000 action": "TV1000 Action",
"tv1000 русское кино": "TV1000 Русское кино",
"tv1000": "TV1000",
"tv5": "TV5",
"ukrainian fashion (украина)": "Ukrainian Fashion (Украина)",
"universal channel": "Universal Channel",
"vh1 classic": "VH1 Classic",
"vh1 european": "VH1 European",
"viasat explorer": "Viasat Explorer",
"viasat history": "Viasat History",
"viasat nature cee": "Viasat Nature CEE",
"viasat sport": "Viasat Sport",
"world fashion channel": "World Fashion Channel",
"world music channel": "World Music Channel",
"zee-tv": "Zee-TV",
"zooпарк": "Zooпарк",
"авто плюс": "Авто Плюс",
"агро-тв": "АГРО-ТВ",
"беларусь-24": "Беларусь-24",
"боец": "Боец",
"бойцовский клуб": "Бойцовский клуб",
"вопросы и ответы": "Вопросы и ответы",
"время": "Время",
"всегда с тобой": "Всегда с тобой",
"девятый (орбита)": "Девятый (Орбита)",
"детский мир + телеклуб": "Детский мир + Телеклуб",
"детский мир": "Детский мир",
"детский": "Детский",
"дождь": "Дождь",
"дом кино": "Дом кино",
"домашние животные": "Домашние животные",
"драйв": "Драйв",
"еврокино": "Еврокино",
"еда hd": "ЕДА HD",
"еда": "ЕДА",
"живи!": "ЖИВИ!",
"загородная жизнь": "Загородная жизнь",
"загородный": "Загородный",
"закон-тв": "Закон-ТВ",
"здоровое тв": "Здоровое ТВ",
"знание": "Знание",
"зоо тв": "Зоо ТВ",
"иллюзион +": "Иллюзион +",
"инва медиа тв": "ИНВА МЕДИА ТВ",
"индия тв": "Индия ТВ",
"интер": "Интер",
"интер украина": "Интер",
"интересное тв": "Интересное ТВ",
"к1": "К1",
"канал disney": "Канал Disney",
"карусель": "Карусель",
"кино плюс": "КИНО ПЛЮС",
"киноклуб": "Киноклуб",
"кинолюкс": "Кинолюкс",
"киномания": "Киномания",
"кинопоказ hd-1": "Кинопоказ HD-1",
"кинопоказ hd-2": "Кинопоказ HD-2",
"кинопоказ": "Кинопоказ",
"киносоюз": "Киносоюз",
"кинохит": "Кинохит",
"комеди тв": "Комеди ТВ",
"comedy tv": "Комеди ТВ",
"комедия тв": "Комедия ТВ",
"комсомольская правда": "Комсомольская правда",
"кто есть кто": "Кто есть кто",
"культура": "Культура",
"россия культура": "Культура",
"кухня тв": "Кухня ТВ",
"кхл": "КХЛ",
"ля-минор": "Ля-Минор",
"м1": "М1",
"мать и дитя": "Мать и дитя",
"мир сериала": "Мир сериала",
"мир": "МИР",
"нтв мир": "МИР",
"много тв": "Много ТВ",
"моя планета": "Моя Планета",
"мужской": "Мужской",
"муз-тв": "МУЗ-ТВ",
"музыка первого": "Музыка Первого",
"мультимания": "Мультимания",
"нано тв": "Нано ТВ",
"настоящее страшное телевидение": "Настоящее Страшное Телевидение",
"наука 2.0": "Наука 2.0",
"наше кино": "Наше кино",
"наше новое кино": "Наше Новое Кино",
"недвижимость": "Недвижимость",
"новый канал": "Новый канал",
"новый канал украина": "Новый канал",
"ностальгия": "Ностальгия",
"нтв": "НТВ",
"нтв-плюс баскетбол": "НТВ-ПЛЮС Баскетбол",
"нтв-плюс наш футбол": "НТВ-ПЛЮС Наш футбол",
"нтв-плюс спорт онлайн": "НТВ-ПЛЮС Спорт Онлайн",
"нтв-плюс спорт плюс": "НТВ-ПЛЮС Спорт Плюс",
"нтв-плюс спорт": "НТВ-ПЛЮС Спорт",
"нтв-плюс теннис": "НТВ-ПЛЮС Теннис",
"нтв-плюс футбол 2": "НТВ-ПЛЮС Футбол 2",
"нтв-плюс футбол": "НТВ-ПЛЮС Футбол",
"нтн": "НТН",
"о2тв": "О2ТВ",
"оружие": "Оружие",
"ост": "ОСТ",
"открытый мир": "Открытый Мир",
"охота и рыбалка": "Охота и рыбалка",
"охотник и рыболов": "Охотник и Рыболов",
"парк развлечений": "Парк развлечений",
"первый hd": "ПЕРВЫЙ HD",
"первый интернет канал": "Первый Интернет Канал",
"первый метео": "Первый метео",
"первый национальный украина": "Первый национальный Украина",
"первый украина": "Первый национальный Украина",
"первый образовательный": "Первый образовательный",
"первый": "Первый",
"первый канал": "Первый",
"пиксель": "Пиксель",
"премьера": "Премьера",
"просвещение": "Просвещение",
"психология 21": "Психология 21",
"радость моя": "Радость Моя",
"раз тв": "Раз ТВ",
"рбк": "РБК",
"рен тв": "РЕН ТВ",
"ретро тв": "Ретро ТВ",
"ржд": "РЖД",
"россия 2": "Россия 2",
"россия hd": "РОССИЯ HD",
"россия": "РОССИЯ HD",
"ртв - любимое кино": "РТВ - Любимое кино",
"русский иллюзион": "Русский Иллюзион",
"русский роман": "Русский роман",
"русский экстрим": "Русский Экстрим",
"сарафан": "Сарафан",
"синергия тв": "Синергия ТВ",
"совершенно секретно": "Совершенно секретно",
"союз": "Союз",
"спас тв": "Спас ТВ",
"спорт 1 hd": "Спорт 1 HD",
"спорт 1": "Спорт 1",
"спорт союз": "Спорт Союз",
"спорт": "Спорт",
"стб": "СТБ",
"стб украина": "СТБ",
"страна": "Страна",
"тбн": "ТБН",
"театр": "Театр",
"телекафе": "Телекафе",
"телеклуб": "Телеклуб",
"телепутешествия hd": "Телепутешествия HD",
"телепутешествия": "Телепутешествия",
"тет": "ТЕТ",
"тет украина": "ТЕТ",
"тин тв": "Тин ТВ",
"тнв": "ТНВ",
"тнв-планета": "ТНВ-планета",
"тонус-тв": "Тонус-ТВ",
"тро": "ТРО",
"туринфо": "ТурИнфо",
"украина": "Украина",
"улыбка ребенка": "Улыбка Ребенка",
"усадьба": "Усадьба",
"успех": "Успех",
"феникс+ кино": "Феникс+ Кино",
"футбол": "Футбол",
"чп.info": "ЧП.Info",
"шансон-tb": "Шансон-TB",
"эгоист тв": "Эгоист ТВ",
"ю": "Ю",
"юмор box": "Юмор BOX",
}