# -*- coding: utf-8 -*-	
dc={
"2x2" : "d001",
"дождь" : "d002",
"домашний" : "d003",
"звезда" : "d004",
"карусель" : "d005",
"мир" : "d006",
"нтв" : "d007",
"первый канал" : "d008",
"перец" : "d009",
"пятый канал" : "d010",
"рен тв" : "d011",
"россия 1" : "d012",
"россия 2" : "d013",
"россия 24" : "d014",
"россия к" : "d015",
"ртр" : "d016",
"стс" : "d017",
"тв 3" : "d018",
"твц" : "d019",
"тнт" : "d020",
"amedia premium" : "amediahd",
"diva universal" : "d022",
"fox" : "d023",
"fox life" : "d024",
"тв21" : "d025",
"rtvi" : "rtvi",
"tv 1000 action" : "d0065",
"tv 1000 east"	: "d0064",
"tv 1000 русское кино" : "d0063",
"дом кино" : "d026",
"индия" : "d027",
"кинолюкс" : "d028",
"кино плюс" : "kinoplusntv",
"много tv" : "mnogotv",
"наше любимое кино" : "nahse_lybimoe_kino",
"кинохит" : "d029",
"наше кино" : "d030",
"наше новое кино" : "d031",
"премьера" : "d032",
"cartoon network" : "cartoon_network",
"disney" : "d033",
"gulli" : "d034",
"jimjam" : "d035",
"nick jr." : "d036",
"nickelodeon" : "d037",
"tiji" : "d038",
"детский мир/телеклуб" : "detskiy_mir",
"моя дитина" : "maja_detina",
"авто плюс" : "d041",
"еда" : "d042",
"кухня" : "d043",
"музыка первого" : "d044",
"ост тв" : "d045",
"шансон" : "d046",
"ю тв" : "d047",
"24 док" : "d048",
"24 техно" : "d049",
"animal planet" : "d050",
"amazing life" : "amazing_life",
"da vinci learning" : "d051",
"discovery" : "d052",
"discovery science" : "d053",
"discovery world" : "d054",
"national geographic" : "d055",
"nat geo wild" : "nat_geo_wild",
"investigation discovery" : "id_investigation_discovery",
"загородная жизнь" : "d056",
"наука 2.0" : "d057",
"рбк" : "d058",
"euronews" : "euronews",
"history" : "history",
"eurosport" : "d059",
"eurosport 2" : "d060",
"viasat sport" : "d061",
"нтв+ баскетбол" : "d062",
"боец" : "d063",
"бойцовский клуб" : "d064",
"кхл тв" : "d065",
"нтв+ наш футбол" : "d066",
"нтв+ спорт" : "d067",
"нтв+ спорт союз" : "d068",
"нтв+ теннис" : "d069",
"нтв+ футбол" : "d070",
"нтв+ футбол 2" : "d071",
"нтв+ спортхит" : "ntvsporthit",
"охотник и рыболов" : "d072",
"спорт" : "d073",
"спорт 1" : "d074",
"нтв+ спорт плюс" : "d075",
"baltijos tv btv" : "d076",
"lietuvas ritas" : "d077",
"lnk" : "d078",
"lnt" : "d079",
"ltv1 latvia" : "d080",
"ltv7" : "d081",
"tv 1 (lithuania)" : "d082",
"tv3 latvia" : "d083",
"tv5 riga" : "d084",
"1+1" : "d085",
"ictv" : "d086",
"интер" : "d087",
"интер+" : "d088",
"первый деловой" : "d089",
"стб" : "d090",
"comedy tv" : "comedy_tv",
"travel" : "travel_channel",
"ocean tv" : "ocean_tv",
"rtg tv" : "rtg",
"tlc" : "tlc1",
"hd кино" : "d096",
"hd кино 2" : "d097",
"первый hd" : "d098",
"россия hd" : "d099",
"спорт 1 hd" : "d100",
"ru tv" : "d1066",
"европа+" : "d1122",
"иллюзион+" : "d1800_1",
"моя планета" : "d181",
"совершенно секретно" : "d182",
"sony sci fi" : "d101",
"nano tv" : "russkij_illusion",
"русский иллюзион" : "russkij_illusion_1",
"tdk" : "tdk",
"пятница" : "pyatnitsa",
"отр" : "otr",
"x sport" : "xsport",
"история" : "istoriya",
"viasat explorer" : "viasat_explorer",
"viasat history" : "viasat_history",
"viasat nature" : "viasat_nature",
"кто есть кто" : "kto_est_kto",
"мужской" : "muzkoy",
"ностальгия" : "nostalgy",
"парк развлечений" : "park_razvl_1",		
"первый образовательный" : "perviy_nac",
"успех" : "uspeh",
"2+2" : "2+2_ua",
"5 канал" : "5_kanal_ua",
"qtv" : "qtv",
"м1" : "m1",
"м2" : "m2",
"нло тв" : "nlo_tv",
"новый канал" : "noviy_kanal",
"нтн" : "ntn_ua",
"первый национальный" : "perviy_nac",
"просвещение" : "procveschenie",
"плюс плюс" : "plus_plus",
"телеканал футбол" : "telekanal_futbol",
"телеканал украина" : "ukraina",
"спорт 1 украина " : "sport1_ua",
"спорт 2 украина " : "sport2_ua",
"твi" : "tbi_ua",
"тонис" : "tonis",
"тет" : "tet_ua",
"news 24" : "telekanal24",
"футбол 1" : "futbol",
"футбол 2" : "futbol_plus",
"armenia tv" : "d0025",
"lider tv" : "lider_tv",
"bbc world" : "bbcworld",
"cnn international" : "cnninternational",
"docubox hd" : "docubox_hd",
"fightbox hd" : "fightbox_hd",
"filmbox hd" : "filmbox_hd",
"fun and fastbox hd" : "funandfastbox_hd",
"киноклуб" : "kinoklub",
"sony turbo" : "sonyturbo",
"tnt film" : "tnt_film",
"tv 1000 comedy hd" : "tv1000_comedy_hd",
"tv 1000 megahit hd" : "tv1000_megahit_hd",
"tv 1000 premium hd" : "tv1000_premium_hd",
"iconcerts":"iconcerts",
"tv 3+" : "tv3plus",
"кинопоказ 1 hd" : "kinopokaz1_hd",
"кинопоказ 2 hd" : "kinopokaz2_hd",
"кинопремиум hd" : "kinopremium",
"наше hd" : "nashehd",
"остросюжетное hd" : "ostrosugetnoe",
"семейное hd" : "semejnoe_hd",
"сериал hd" : "serial_hd",
"телепутешествия hd" : "teletravel_hd",
"motors tv" : "motorstv",
"eureka hd" : "eureka_hd_ru",
"animal family hd" : "animal_family_hd_ru",
"русский роман" : "rus_roman",
"k2" : "k2",
"сарафан тв" : "sarafan"
} 